# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master
- develop

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  packageVersion: '1.0.0-develop'
  vmImage: 'windows-latest'

stages:
- stage: build_test
  pool:
    vmImage: '$(vmImage)'
  jobs:
  - job: build
    steps:
    - task: NuGetToolInstaller@1
    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'
    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
    - task: VSTest@2
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: |
          **\*UnitTests.dll
          **\bin\$(BuildConfiguration)\**\*UnitTests.dll
          **\tests\SpecFlow.Variants.UnitTests\bin\Release\SpecFlow.Variants.UnitTests.dll
          d:\a\1\a\tests\SpecFlow.Variants.UnitTests\bin\Release\SpecFlow.Variants.UnitTests.dll
          !**\*TestAdapter.dll
          !**\obj\**
          !**\xunit.runner.visualstudio.testadapter.dll
          !**\xunit.runner.visualstudio.dotnetcore.testadapter.dll
    #- task: CopyFiles@2
    #  inputs:
    #    contents: '**\SpecFlow.Variants.UnitTests\bin\$(buildConfiguration)\**'
    #    targetFolder: $(Build.ArtifactStagingDirectory)
  - job: run_unit_tests
    dependsOn: build
    steps:
    - task: VSTest@2
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: |
          **\*UnitTests.dll
          **\bin\$(BuildConfiguration)\**\*UnitTests.dll
          **\tests\SpecFlow.Variants.UnitTests\bin\Release\SpecFlow.Variants.UnitTests.dll
          d:\a\1\a\tests\SpecFlow.Variants.UnitTests\bin\Release\SpecFlow.Variants.UnitTests.dll
          !**\*TestAdapter.dll
          !**\obj\**
          !**\xunit.runner.visualstudio.testadapter.dll
          !**\xunit.runner.visualstudio.dotnetcore.testadapter.dll
        searchFolder: '$(Build.ArtifactStagingDirectory)'

- stage: deploy_package
  pool:
    vmImage: '$(vmImage)'
  jobs:
  - job: deploy_prerelease
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))  
    steps:
    - task: NuGetCommand@2
      inputs:
        command: 'pack'
        packagesToPack: '**/*.nuspec'
        versioningScheme: 'byEnvVar'
        versionEnvVar: '$(packageVersion)'
    - task: NuGetCommand@2
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
        nuGetFeedType: 'internal'
        publishVstsFeed: '8cc48bdf-30e3-409a-9f50-1d2e6944e896/ee5c684a-40df-48ba-b303-1a8a5ca628e5'
#    - job: deploy_major
#      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))